spring:
  datasource:
    username: root
    password: Admin@123
    url: jdbc:mysql://localhost:3306/emp
    driver-class-name: com.mysql.cj.jdbc.Driver 
      #properties.hibernate.dialect=org.hibernate.dialect.My8SQLDialect

  jpa:
    database-platform: 
    hibernate:
        dialect: MySQLDialect
        ddl-auto: update
        show-sql: true
    
   